[workspace]
resolver = "2"
members = ["tui-*"]

[workspace.package]
authors = ["Joshka"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/joshka/tui-widgets"
edition = "2021"
rust-version = "1.63.0"

[workspace.dependencies]
ratatui = { version = "0.27.0", default-features = false }

[package]
name = "tui-widgets"
description = "A collection of useful widgets for building terminal user interfaces using Ratatui"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[features]
default = ["full"]
## All widgets
full = ["big-text", "scrollview"]
## Enables the [`big_text`] widget
big-text = ["tui-big-text"]
## Enables the [`scrollview`] widget
scrollview = ["tui-scrollview"]

[dependencies]
document-features = "0.2.10"
ratatui = { workspace = true }
tui-big-text = { version = "0.4.5", path = "tui-big-text", optional = true }
tui-scrollview = { version = "0.3.7", path = "tui-scrollview", optional = true }
